dist: trusty
sudo: false
language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
      - qemu-system-i386
install:
  - pip install -e '.[tests]'
script:
  - py.test --pylama
