notifications:
  email:
    on_success: change
    on_failure: change
dist: trusty
sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
      - qemu-system-i386
      - qemu-utils
install:
  - pip install -e '.[tests]'
script:
  - wget --quiet netng.pl/routeros_test_images/routeros_6.33.3.qcow2 -O images/routeros_6.33.3.qcow2
  - py.test --pylama
deploy:
  provider: pypi
  user: lkostka
  password: $PYPI_PASS
  on:
    tags: true
    python: 3.6
